/* eslint-disable quote-props, max-len, object-property-newline */
import * as type from 'utils/type.config';

/**
 * Created by Sam on 2016/12/28.
 * Copyright © 2016年 JX. All rights reserved.
 */

const {
  GAME_CATEGORY: {SHISHICAI, PK10, PCDANDAN, FIVE11, KUAI3, HAPPY10, NONE},
  CUSTOM_GAME_CATEGORY: {G1, PK, QXC, SIX, XY},
} = type;

export const idsToOmit = ['HF_FJD11'];

export const gamesMap = [
  {
    category: PK10,
    gameSettingsMap: PK10,
    gameUniqueId: 'HF_BJPK10',
    gameNameInChinese: '北京PK拾',
    issueCountPerDay: 44,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: PK10,
    gameSettingsMap: PK10,
    gameUniqueId: 'HF_LFPK10',
    gameNameInChinese: '二分PK拾',
    issueCountPerDay: 660,
    issueFrequency: 'HIGH',
    issueDuration: '2分钟',
  },
  {
    category: PK10,
    gameSettingsMap: PK10,
    gameUniqueId: 'HF_FFPK10',
    gameNameInChinese: '分分PK拾',
    issueCountPerDay: 1320,
    issueFrequency: 'HIGH',
    issueDuration: '1分钟',
  },
  {
    category: PK10,
    gameSettingsMap: PK10,
    gameUniqueId: 'HF_WFPK10',
    gameNameInChinese: '五分PK拾',
    issueCountPerDay: 265,
    issueFrequency: 'HIGH',
    issueDuration: '5分钟',
  },
  {
    category: FIVE11,
    gameSettingsMap: FIVE11,
    gameUniqueId: 'HF_FJD11',
    gameNameInChinese: '福建11选5',
    issueCountPerDay: 90,
    issueFrequency: 'HIGH',
    issueDuration: '10分钟',
  },
  {
    category: FIVE11,
    gameSettingsMap: FIVE11,
    gameUniqueId: 'HF_AHD11',
    gameNameInChinese: '安徽11选5',
    issueCountPerDay: 40,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: FIVE11,
    gameSettingsMap: FIVE11,
    gameUniqueId: 'HF_GDD11',
    gameNameInChinese: '广东11选5',
    issueCountPerDay: 42,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: FIVE11,
    gameSettingsMap: FIVE11,
    gameUniqueId: 'HF_JXD11',
    gameNameInChinese: '江西11选5',
    issueCountPerDay: 42,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: FIVE11,
    gameSettingsMap: FIVE11,
    gameUniqueId: 'HF_SDD11',
    gameNameInChinese: '山东11选5',
    issueCountPerDay: 43,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: FIVE11,
    gameSettingsMap: FIVE11,
    gameUniqueId: 'HF_SHD11',
    gameNameInChinese: '上海11选5',
    issueCountPerDay: 45,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: FIVE11,
    gameSettingsMap: FIVE11,
    gameUniqueId: 'HF_JSD11',
    gameNameInChinese: '江苏11选5',
    issueCountPerDay: 82,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: NONE,
    gameSettingsMap: G1,
    gameUniqueId: 'X3D',
    gameNameInChinese: '福彩3D',
    issueCountPerDay: 1,
    issueFrequency: 'LOW',
    issueDuration: '1天',
  },
  {
    category: NONE,
    gameSettingsMap: G1,
    gameUniqueId: 'HF_JS3D',
    gameNameInChinese: '极速3D',
    issueCountPerDay: 264,
    issueFrequency: 'HIGH',
    issueDuration: '5分钟',
  },
  {
    category: PCDANDAN,
    gameSettingsMap: PCDANDAN,
    gameUniqueId: 'HF_LF28',
    gameNameInChinese: '幸运28',
    issueCountPerDay: 660,
    issueFrequency: 'HIGH',
    issueDuration: '2分钟',
  },
  {
    category: PCDANDAN,
    gameSettingsMap: PCDANDAN,
    gameUniqueId: 'HF_BJ28',
    gameNameInChinese: '北京28',
    issueCountPerDay: 660,
    issueFrequency: 'HIGH',
    issueDuration: '5分钟',
  },
  {
    category: PCDANDAN,
    gameSettingsMap: PCDANDAN,
    gameUniqueId: 'BJ28',
    gameNameInChinese: '北京28',
    issueCountPerDay: 1,
    issueFrequency: 'LOW',
    issueDuration: '1天',
  },
  {
    category: KUAI3,
    gameSettingsMap: KUAI3,
    gameUniqueId: 'HF_AHK3',
    gameNameInChinese: '安徽快3',
    issueCountPerDay: 40,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: KUAI3,
    gameSettingsMap: KUAI3,
    gameUniqueId: 'HF_BJK3',
    gameNameInChinese: '北京快3',
    issueCountPerDay: 44,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: KUAI3,
    gameSettingsMap: KUAI3,
    gameUniqueId: 'HF_GXK3',
    gameNameInChinese: '广西快3',
    issueCountPerDay: 40,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: KUAI3,
    gameSettingsMap: KUAI3,
    gameUniqueId: 'HF_JLK3',
    gameNameInChinese: '吉林快3',
    issueCountPerDay: 41,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: KUAI3,
    gameSettingsMap: KUAI3,
    gameUniqueId: 'HF_JSK3',
    gameNameInChinese: '江苏快3',
    issueCountPerDay: 41,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: KUAI3,
    gameSettingsMap: KUAI3,
    gameUniqueId: 'HF_LFK3',
    gameNameInChinese: '二分快3',
    issueCountPerDay: 660,
    issueFrequency: 'HIGH',
    issueDuration: '2分钟',
  },
  {
    category: KUAI3,
    gameSettingsMap: KUAI3,
    gameUniqueId: 'HF_FFK3',
    gameNameInChinese: '分分快3',
    issueCountPerDay: 1320,
    issueFrequency: 'HIGH',
    issueDuration: '1分钟',
  },
  {
    category: KUAI3,
    gameSettingsMap: KUAI3,
    gameUniqueId: 'HF_HBK3',
    gameNameInChinese: '河北快3',
    issueCountPerDay: 41,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: KUAI3,
    gameSettingsMap: KUAI3,
    gameUniqueId: 'HF_GSK3',
    gameNameInChinese: '甘肃快3',
    issueCountPerDay: 36,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: KUAI3,
    gameSettingsMap: KUAI3,
    gameUniqueId: 'HF_SHK3',
    gameNameInChinese: '上海快3',
    issueCountPerDay: 41,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: KUAI3,
    gameSettingsMap: KUAI3,
    gameUniqueId: 'HF_WFK3',
    gameNameInChinese: '五分快3',
    issueCountPerDay: 265,
    issueFrequency: 'HIGH',
    issueDuration: '5分钟',
  },
  {
    category: HAPPY10,
    gameSettingsMap: HAPPY10,
    gameUniqueId: 'HF_CQKL10F',
    gameNameInChinese: '重庆快乐十分',
    issueCountPerDay: 48,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: HAPPY10,
    gameSettingsMap: HAPPY10,
    gameUniqueId: 'HF_GDKL10F',
    gameNameInChinese: '广东快乐十分',
    issueCountPerDay: 42,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: NONE,
    gameSettingsMap: SIX,
    gameUniqueId: 'TW_MARK_SIX',
    gameNameInChinese: '台湾大乐透',
    issueCountPerDay: 1,
    issueFrequency: 'LOW',
    issueDuration: '2天或3天',
  },
  {
    category: NONE,
    gameSettingsMap: SIX,
    gameUniqueId: 'SG_MARK_SIX',
    gameNameInChinese: '新加坡六合彩',
    issueCountPerDay: 1,
    issueFrequency: 'LOW',
    issueDuration: '2天或3天',
  },
  {
    category: NONE,
    gameSettingsMap: SIX,
    gameUniqueId: 'MC_MARK_SIX',
    gameNameInChinese: '澳门六合彩',
    issueCountPerDay: 1,
    issueFrequency: 'LOW',
    issueDuration: '1天',
  },
  {
    category: NONE,
    gameSettingsMap: SIX,
    gameUniqueId: 'MARK_SIX',
    gameNameInChinese: '香港六合彩',
    issueCountPerDay: 1,
    issueFrequency: 'LOW',
    issueDuration: '2天或3天',
  },
  {
    category: NONE,
    gameSettingsMap: SIX,
    gameUniqueId: 'HF_JSMS',
    gameNameInChinese: '极速六合彩',
    issueCountPerDay: 264,
    issueFrequency: 'HIGH',
    issueDuration: '5分钟',
  },
  {
    category: NONE,
    gameSettingsMap: PK,
    gameUniqueId: 'HF_LFKLPK',
    gameNameInChinese: '幸运扑克',
    issueCountPerDay: 660,
    issueFrequency: 'HIGH',
    issueDuration: '2分钟',
  },
  {
    category: NONE,
    gameSettingsMap: PK,
    gameUniqueId: 'HF_XYPK',
    gameNameInChinese: '新幸运扑克',
    issueCountPerDay: 660,
    issueFrequency: 'HIGH',
    issueDuration: '2分钟',
  },
  {
    category: NONE,
    gameSettingsMap: G1,
    gameUniqueId: 'PL3',
    gameNameInChinese: '排列3',
    issueCountPerDay: 1,
    issueFrequency: 'LOW',
    issueDuration: '1天',
  },
  {
    category: SHISHICAI,
    gameSettingsMap: SHISHICAI,
    gameUniqueId: 'HF_CQSSC',
    gameNameInChinese: '重庆时时彩',
    issueCountPerDay: 59,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: SHISHICAI,
    gameSettingsMap: SHISHICAI,
    gameUniqueId: 'HF_LFSSC',
    gameNameInChinese: '二分时时彩',
    issueCountPerDay: 660,
    issueFrequency: 'HIGH',
    issueDuration: '2分钟',
  },
  {
    category: SHISHICAI,
    gameSettingsMap: SHISHICAI,
    gameUniqueId: 'HF_TJSSC',
    gameNameInChinese: '天津时时彩',
    issueCountPerDay: 42,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: SHISHICAI,
    gameSettingsMap: SHISHICAI,
    gameUniqueId: 'HF_XJSSC',
    gameNameInChinese: '新疆时时彩',
    issueCountPerDay: 48,
    issueFrequency: 'HIGH',
    issueDuration: '20分钟',
  },
  {
    category: SHISHICAI,
    gameSettingsMap: SHISHICAI,
    gameUniqueId: 'HF_FFSSC',
    gameNameInChinese: '分分时时彩',
    issueCountPerDay: 1320,
    issueFrequency: 'HIGH',
    issueDuration: '1分钟',
  },
  {
    category: SHISHICAI,
    gameSettingsMap: SHISHICAI,
    gameUniqueId: 'PL5',
    gameNameInChinese: '排列5',
    issueCountPerDay: 1,
    issueFrequency: 'LOW',
    issueDuration: '1天',
  },
  {
    category: SHISHICAI,
    gameSettingsMap: SHISHICAI,
    gameUniqueId: 'HF_WFSSC',
    gameNameInChinese: '五分时时彩',
    issueCountPerDay: 265,
    issueFrequency: 'HIGH',
    issueDuration: '5分钟',
  },
  {
    category: SHISHICAI,
    gameSettingsMap: SHISHICAI,
    gameUniqueId: 'HF_TXFFC',
    gameNameInChinese: '腾讯分分彩',
    issueCountPerDay: 1440,
    issueFrequency: 'HIGH',
    issueDuration: '1分钟',
  },
  {
    category: SHISHICAI,
    gameSettingsMap: SHISHICAI,
    gameUniqueId: 'HF_BJSSC',
    gameNameInChinese: '北京时时彩',
    issueCountPerDay: 179,
    issueFrequency: 'HIGH',
    issueDuration: '5分钟',
  },
  {
    category: SHISHICAI,
    gameSettingsMap: SHISHICAI,
    gameUniqueId: 'HF_TWSSC',
    gameNameInChinese: '台湾时时彩',
    issueCountPerDay: 203,
    issueFrequency: 'HIGH',
    issueDuration: '5分钟',
  },
  {
    category: SHISHICAI,
    gameSettingsMap: SHISHICAI,
    gameUniqueId: 'FLCKL8',
    gameNameInChinese: '福利彩快乐8',
    issueCountPerDay: 1,
    issueFrequency: 'LOW',
    issueDuration: '1天',
  },
  {
    category: NONE,
    gameSettingsMap: G1,
    gameUniqueId: 'HF_SHSSL',
    gameNameInChinese: '上海时时乐',
    issueCountPerDay: 23,
    issueFrequency: 'HIGH',
    issueDuration: '30分钟',
  },
  {
    category: PK10,
    gameSettingsMap: PK10,
    gameUniqueId: 'HF_AZXY10',
    gameNameInChinese: '澳洲幸运10',
    issueCountPerDay: 180,
    issueFrequency: 'HIGH',
    issueDuration: '5分钟',
  },
  {
    category: HAPPY10,
    gameSettingsMap: HAPPY10,
    gameUniqueId: 'HF_AZXY8',
    gameNameInChinese: '澳洲幸运8',
    issueCountPerDay: 180,
    issueFrequency: 'HIGH',
    issueDuration: '5分钟',
  },
  {
    category: SHISHICAI,
    gameSettingsMap: SHISHICAI,
    gameUniqueId: 'HF_AZXY5',
    gameNameInChinese: '澳洲幸运5',
    issueCountPerDay: 180,
    issueFrequency: 'HIGH',
    issueDuration: '5分钟',
  },
  // {
  //   category: PK10,
  //   gameSettingsMap: XY,
  //   gameUniqueId: 'HF_MXYFT',
  //   gameNameInChinese: '幸运飞艇(经典)',
  //   issueCountPerDay: 180,
  //   issueFrequency: 'HIGH',
  //   issueDuration: '5分钟',
  // },
  {
    category: PK10,
    gameSettingsMap: XY,
    gameUniqueId: 'HF_XYFT',
    gameNameInChinese: '幸运飞艇',
    issueCountPerDay: 180,
    issueFrequency: 'HIGH',
    issueDuration: '5分钟',
  },
  {
    category: PK10,
    gameSettingsMap: XY,
    gameUniqueId: 'HF_LFFT',
    gameNameInChinese: '二分飞艇',
    issueCountPerDay: 180,
    issueFrequency: 'HIGH',
    issueDuration: '2分钟',
  },
  {
    category: PK10,
    gameSettingsMap: XY,
    gameUniqueId: 'HF_FFFT',
    gameNameInChinese: '分分飞艇',
    issueCountPerDay: 360,
    issueFrequency: 'HIGH',
    issueDuration: '1分钟',
  },
  {
    category: PK10,
    gameSettingsMap: XY,
    gameUniqueId: 'HF_XYSM',
    gameNameInChinese: '幸运赛马',
    issueCountPerDay: 264,
    issueFrequency: 'HIGH',
    issueDuration: '5分钟',
  },
  {
    category: NONE,
    gameSettingsMap: QXC,
    gameUniqueId: 'QXC',
    gameNameInChinese: '七星彩',
    issueCountPerDay: 1,
    issueFrequency: 'LOW',
    issueDuration: '2/3天',
  },
];

export const gameRules = {
  DN: {
    sections: type.ALL_RANK,
    set: [type.LEADNUM_1_10],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: [
      '1-10',
      '1-10',
      '1-10',
      '1-10',
      '1-10',
      '1-10',
      '1-10',
      '1-10',
      '1-10',
      '1-10',
    ],
  },
  SP: {
    sections: type.UNITS_B_S_G,
    set: [type.NUM_0_9],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-10', '1-10', '1-10'],
  },
  UNFIX_1: {
    sections: type.UNFIX,
    set: [type.NUM_0_9],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-10'],
  },
  UNFIX_2: {
    sections: type.UNFIX,
    set: [type.NUM_0_9],
    uniqueInt: 2,
    formula: type.GROUP_2,
    minimumRowPick: 1,
    pickRange: ['2-10'],
  },
  GS: {
    sections: type.SUM_VALUES,
    set: [type.NUM_0_27],
    formula: type.SUM,
    minimumRowPick: 1,
    pickRange: ['1-28'],
  },
  G3S: {
    sections: type.SUM_VALUES,
    set: [type.NUM_1_26],
    formula: type.SUM,
    minimumRowPick: 1,
    pickRange: ['1-26'],
  },
  G6S: {
    sections: type.SUM_VALUES,
    set: [type.NUM_3_24],
    formula: type.SUM,
    minimumRowPick: 1,
    pickRange: ['1-22'],
  },
  GYHZ: {
    sections: type.SUM_VALUES,
    set: [type.NUM_3_19],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-17'],
  },
  GYH: {
    sections: type.SUM_VALUES,
    set: [type.BS_DS],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-8'],
  },
  GRP2: {
    sections: type.PICK_NUM,
    set: [type.NUM_0_9],
    uniqueInt: 2,
    formula: type.GROUP_2,
    minimumRowPick: 1,
    pickRange: ['2-10'],
  },
  GRP3: {
    sections: type.PICK_NUM,
    set: [type.NUM_0_9],
    formula: type.GROUP_3,
    minimumRowPick: 1,
    pickRange: ['2-10'],
  },
  GRP6: {
    sections: type.PICK_NUM,
    set: [type.NUM_0_9],
    formula: type.GROUP_6,
    minimumRowPick: 1,
    pickRange: ['3-10'],
  },
  D1: {
    sections: type.TOP_ONE_RANK,
    set: [type.LEADNUM_1_10],
    formula: type.DUPLEX,
    minimumRowPick: 1,
    pickRange: ['1-10'],
  },
  D2: {
    sections: type.UNITS_S_G,
    set: [type.NUM_0_9],
    formula: type.DUPLEX,
    minimumRowPick: 2,
    pickRange: ['1-10', '1-10'],
  },
  D3: {
    sections: type.UNITS_B_S_G,
    set: [type.NUM_0_9],
    minimumRowPick: 3,
    pickRange: ['1-10', '1-10', '1-10'],
  },
  D5: {
    sections: type.UNITS_W_Q_B_S_G,
    set: [type.NUM_0_9],
    formula: type.DUPLEX,
    minimumRowPick: 5,
    pickRange: ['1-10', '1-10', '1-10', '1-10', '1-10'],
  },
  GT2: {
    sections: type.TOP_TWO_RANK,
    set: [type.LEADNUM_1_10],
    formula: type.TOP_TWO_BET,
    minimumRowPick: 2,
    pickRange: ['1-10', '1-10'],
  },
  GT3: {
    sections: type.TOP_THREE_RANK,
    set: [type.LEADNUM_1_10],
    formula: type.TOP_THREE_BET,
    minimumRowPick: 3,
    pickRange: ['1-10', '1-10', '1-10'],
  },
  F2IO: {
    sections: type.UNITS_B_S,
    set: [type.NUM_0_9],
    formula: type.DUPLEX,
    minimumRowPick: 2,
    pickRange: ['1-10', '1-10'],
  },
  L2IO: {
    sections: type.UNITS_S_G,
    set: [type.NUM_0_9],
    formula: type.DUPLEX,
    minimumRowPick: 2,
    pickRange: ['1-10', '1-10'],
  },
  BSOE: {
    set: [type.BSOE],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-4'],
  },
  BSOE2: {
    set: [type.BSOE],
    formula: type.DUPLEX,
    minimumRowPick: 2,
    pickRange: ['1-4', '1-4'],
  },
  BSOE3: {
    set: [type.BSOE],
    formula: type.DUPLEX,
    minimumRowPick: 3,
    pickRange: ['1-4', '1-4', '1-4'],
  },
  DTBSOE: {
    set: [type.DRAGON_TIGER_BSOE],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-6'],
  },
  BS_DS: {
    set: [type.BS_DS],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-8'],
  },
  DTBS_DS: {
    set: [type.DRAGON_TIGER_BS_DS],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-10'],
  },
  Q3Z: {
    sections: type.UNITS_W_Q_B,
    set: [type.LEADNUM_1_11],
    formula: type.TOP_THREE_BET,
    minimumRowPick: 3,
    pickRange: ['1-11', '1-11', '1-11'],
  },
  DT: {
    sections: type.DIRECT_PICK_PULL,
    set: [type.LEADNUM_1_11],
    isUnique: true,
    formula: type.DIRECT_PICK_PULL_BET,
    minimumRowPick: 2,
    bypassValidate: true,
  },
  PN: {
    sections: type.PICK_NUM,
    set: [type.LEADNUM_1_11],
    formula: type.DIRECT_COMBINE,
    minimumRowPick: 1,
  },
  RC: {
    sections: type.PICK_CARD,
    set: [type.POKER_A_K],
    displaySet: type.POKER_A_K_DISPLAY_TEXT,
    formula: type.DIRECT_COMBINE,
    minimumRowPick: 1,
  },
  R2C_HZ: {
    sections: type.SUM_VALUES,
    set: [type.NUM_0_18],
    openOptions: type.UNITS_W_Q_B_S_G,
    formula: type.SUM__OPEN,
    minimumRowPick: 1,
    pickRange: ['1-19'],
    uniqueInt: 2,
  },
  R3C_HZ: {
    sections: type.SUM_VALUES,
    set: [type.NUM_0_27],
    openOptions: type.UNITS_W_Q_B_S_G,
    formula: type.SUM__OPEN,
    minimumRowPick: 1,
    pickRange: ['1-28'],
    uniqueInt: 3,
  },
  R3C: {
    sections: type.PICK_NUM,
    set: [type.NUM_0_9],
    openOptions: type.UNITS_W_Q_B_S_G,
    minimumRowPick: 1,
    uniqueInt: 3,
  },
  RZ: {
    sections: type.UNITS_W_Q_B_S_G,
    set: [type.NUM_0_9],
    formula: type.COMBO_DUPLEX,
    pickRange: ['1-10', '1-10', '1-10', '1-10', '1-10'],
  },
  TND: {
    sections: type.DRAGON_AND_TIGER,
    set: [type.DRAGON_TIGER_SUM],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-3'],
  },
  POKER3: {
    set: [type.SSC_POKER],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-5'],
  },
  LM2: {
    sections: type.PICK_NUM,
    set: [type.LEADNUM_1_49],
    uniqueInt: 2,
    isUnique: true,
    formula: type.CONNECT_NUM_2,
    minimumRowPick: 1,
    pickRange: ['2-7'],
  },
  LM2_10: {
    sections: type.PICK_NUM,
    set: [type.LEADNUM_1_49],
    uniqueInt: 2,
    isUnique: true,
    formula: type.CONNECT_NUM_2,
    minimumRowPick: 1,
    pickRange: ['2-10'],
  },
  LM3: {
    sections: type.PICK_NUM,
    set: [type.LEADNUM_1_49],
    uniqueInt: 3,
    isUnique: true,
    formula: type.CONNECT_NUM_3,
    minimumRowPick: 1,
  },
  NB: {
    sections: type.PICK_NUM,
    set: [type.LEADNUM_1_49],
    isUnique: true,
    formula: type.DIRECT_COMBINE,
    minimumRowPick: 1,
  },
  KL: {
    set: [type.LEADNUM_1_20],
    formula: type.DIRECT_COMBINE,
    minimumRowPick: 1,
  },
  SHTX: {
    sections: type.PICK_ALL,
    set: [type.TRIPLE_PICK_ALL],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-1'],
  },
  PN_D: {
    sections: type.PICK_NUM,
    set: [type.LEADNUM_1_49],
    formula: type.DUPLEX,
    minimumRowPick: 1,
    pickRange: ['1-49'],
  },
  PN_S: {
    sections: type.PICK_NUM,
    set: [type.LEADNUM_1_49],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-49'],
  },
  C_D: {
    sections: type.CATEGORY,
    formula: type.DUPLEX,
    minimumRowPick: 1,
    pickRange: ['1-12'],
  },
  C_S: {
    sections: type.CATEGORY,
    set: [type.POSITIVE_NUM],
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-13'],
  },
  THDX: {
    sections: type.PICK_CARD,
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-4'],
    showMethod: true,
  },
  ZDX: {
    sections: type.PICK_CARD,
    formula: type.SINGLE,
    minimumRowPick: 1,
    pickRange: ['1-13'],
  },
  LP: {
    sections: type.LUNPAN,
    set: [type.LUNPAN_SET],
    setLunpanIndicator: [type.LUNPAN_NUM_INDICATOR],
    setLunpanSpecialIndicator: [type.LUNPAN_NUM_SPECIAL_INDICATOR],
    setLunpanSpecialDivideIndicator: [type.LUNPAN_NUM_SPECIAL_DIVIDE_INDICATOR],
    setLunpanNum: [type.LUNPAN_BYROW],
    setLunpanNumPickSix: [type.LUNPAN_NUM_PICK_SIX],
    setLunpanNumPickFourFirst: [type.LUNPAN_NUM_PICK_FOUR_FIRST],
    setLunpanNumPickFourSecond: [type.LUNPAN_NUM_PICK_FOUR_SECOND],
    minimumRowPick: 1,
    formula: type.SINGLE,
    pickRange: ['1-83'],
  },
};

export const gameSettingsMap = {
  [PK10]: [
    {
      gameMethod: '定位胆',
      methodId: 'DN',
      gameRules: gameRules.DN,
    },
    {
      gameMethod: '猜第一',
      methodId: 'D1',
      gameRules: gameRules.D1,
    },
    {
      gameMethod: '猜前二',
      methodId: 'GT2',
      gameRules: gameRules.GT2,
    },
    {
      gameMethod: '猜前三',
      methodId: 'GT3',
      gameRules: gameRules.GT3,
    },
    {
      gameMethod: '后一',
      methodId: 'LAST1',
      gameRules: {...gameRules.D1, sections: type.BACK_FIRST_RANK},
    },
    {
      gameMethod: '后二',
      methodId: 'LAST2',
      gameRules: {...gameRules.GT2, sections: type.BACK_TWO_RANK},
    },
    {
      gameMethod: '后三',
      methodId: 'LAST3',
      gameRules: {...gameRules.GT3, sections: type.BACK_THREE_RANK},
    },
    {
      gameMethod: type.RANKS[0],
      methodId: 'DYM',
      gameRules: {...gameRules.DTBS_DS, sections: [type.RANKS[0]]},
    },
    {
      gameMethod: type.RANKS[1],
      methodId: 'DEM',
      gameRules: {...gameRules.DTBS_DS, sections: [type.RANKS[1]]},
    },
    {
      gameMethod: type.RANKS[2],
      methodId: 'DSM',
      gameRules: {...gameRules.DTBS_DS, sections: [type.RANKS[2]]},
    },
    {
      gameMethod: type.RANKS[3],
      methodId: 'DSIM',
      gameRules: {...gameRules.DTBS_DS, sections: [type.RANKS[3]]},
    },
    {
      gameMethod: type.RANKS[4],
      methodId: 'DWUM',
      gameRules: {...gameRules.DTBS_DS, sections: [type.RANKS[4]]},
    },
    {
      gameMethod: '冠亚和值',
      methodId: 'GYHZ',
      gameRules: gameRules.GYHZ,
    },
    {
      gameMethod: '冠亚和',
      methodId: 'GYH',
      gameRules: gameRules.GYH,
    },
  ],
  [FIVE11]: [
    {
      gameMethod: '普通-任选一',
      methodId: 'R1',
      gameRules: {...gameRules.PN, pickRange: ['1-11'], formula: type.SINGLE},
    },
    {
      gameMethod: '普通-任选二',
      methodId: 'R2',
      gameRules: {...gameRules.PN, pickRange: ['2-11']},
    },
    {
      gameMethod: '普通-任选三',
      methodId: 'R3',
      gameRules: {...gameRules.PN, pickRange: ['3-11']},
    },
    {
      gameMethod: '普通-任选四',
      methodId: 'R4',
      gameRules: {...gameRules.PN, pickRange: ['4-11']},
    },
    {
      gameMethod: '普通-任选五',
      methodId: 'R5',
      gameRules: {...gameRules.PN, pickRange: ['5-11']},
    },
    {
      gameMethod: '普通-任选六',
      methodId: 'R6',
      gameRules: {...gameRules.PN, pickRange: ['6-11']},
    },
    {
      gameMethod: '普通-任选七',
      methodId: 'R7',
      gameRules: {...gameRules.PN, pickRange: ['7-11']},
    },
    {
      gameMethod: '普通-任选八',
      methodId: 'R8',
      gameRules: {...gameRules.PN, pickRange: ['8-11']},
    },
    {
      gameMethod: '普通-前一直选',
      methodId: 'Q1Z',
      gameRules: {
        sections: type.UNITS_W,
        set: [type.LEADNUM_1_11],
        formula: type.DUPLEX,
        minimumRowPick: 1,
        pickRange: ['1-11'],
      },
    },
    {
      gameMethod: '普通-前二组选',
      methodId: 'Q2C',
      gameRules: {...gameRules.PN, pickRange: ['2-11']},
    },
    {
      gameMethod: '普通-前二直选',
      methodId: 'Q2Z',
      gameRules: {
        sections: type.UNITS_W_Q,
        set: [type.LEADNUM_1_11],
        formula: type.TOP_TWO_BET,
        minimumRowPick: 2,
        pickRange: ['1-11', '1-11'],
      },
    },
    {
      gameMethod: '普通-前三组选',
      methodId: 'Q3C',
      gameRules: {...gameRules.PN, pickRange: ['3-11']},
    },
    {
      gameMethod: '普通-前三直选',
      methodId: 'Q3Z',
      gameRules: gameRules.Q3Z,
    },
    {
      gameMethod: '胆拖-任选二',
      methodId: 'R2DT',
      gameRules: {
        ...gameRules.DT,
        uniqueInt: 2,
        pickRange: ['1-1', '1-11'],
      },
    },
    {
      gameMethod: '胆拖-任选三',
      methodId: 'R3DT',
      gameRules: {
        ...gameRules.DT,
        uniqueInt: 3,
        pickRange: ['1-2', '2-11'],
      },
    },
    {
      gameMethod: '胆拖-任选四',
      methodId: 'R4DT',
      gameRules: {
        ...gameRules.DT,
        uniqueInt: 4,
        pickRange: ['1-3', '3-11'],
      },
    },
    {
      gameMethod: '胆拖-任选五',
      methodId: 'R5DT',
      gameRules: {
        ...gameRules.DT,
        uniqueInt: 5,
        pickRange: ['1-4', '4-11'],
      },
    },
    {
      gameMethod: '胆拖-任选六',
      methodId: 'R6DT',
      gameRules: {
        ...gameRules.DT,
        uniqueInt: 6,
        pickRange: ['1-5', '5-11'],
      },
    },
    {
      gameMethod: '胆拖-任选七',
      methodId: 'R7DT',
      gameRules: {
        ...gameRules.DT,
        uniqueInt: 7,
        pickRange: ['1-6', '6-11'],
      },
    },
    {
      gameMethod: '胆拖-任选八',
      methodId: 'R8DT',
      gameRules: {
        ...gameRules.DT,
        uniqueInt: 8,
        pickRange: ['1-7', '7-11'],
      },
    },
    {
      gameMethod: '胆拖-前二组选',
      methodId: 'Q2CDT',
      gameRules: {
        ...gameRules.DT,
        uniqueInt: 2,
        pickRange: ['1-1', '1-11'],
      },
    },
    {
      gameMethod: '胆拖-前三组选',
      methodId: 'Q3CDT',
      gameRules: {
        ...gameRules.DT,
        uniqueInt: 3,
        pickRange: ['1-2', '2-11'],
      },
    },
  ],
  [G1]: [
    {
      gameMethod: '三星-直选复式',
      methodId: 'NIO3',
      gameRules: {...gameRules.D3, formula: type.DUPLEX},
    },
    {
      gameMethod: '三星-直选单式',
      betMode: 'single',
      inputMode: 'text',
      methodId: 'NIO3',
      gameRules: {...gameRules.D3, formula: type.DUPLEX},
    },
    {
      gameMethod: '三星-直选和值',
      methodId: 'NS3',
      gameRules: gameRules.GS,
    },
    {
      gameMethod: '三星-组三复式',
      methodId: 'GRP3',
      gameRules: gameRules.GRP3,
    },
    {
      gameMethod: '三星-组三单式',
      betMode: 'single',
      inputMode: 'text',
      methodId: 'GRP3DS',
      gameRules: {
        ...gameRules.GRP3,
        formula: type.GROUP_3__SINGLE,
        pickRange: ['3-10'],
        specialCond: {duplicate: {no: 1, occurence: 2}},
      },
    },
    {
      gameMethod: '三星-组六复式',
      methodId: 'GRP6',
      gameRules: gameRules.GRP6,
    },
    {
      gameMethod: '三星-组六单式',
      betMode: 'single',
      inputMode: 'text',
      methodId: 'GRP6',
      gameRules: gameRules.GRP6,
    },
    {
      gameMethod: '三星-组三和值',
      methodId: 'G3S',
      gameRules: gameRules.G3S,
    },
    {
      gameMethod: '三星-组六和值',
      methodId: 'G6S',
      gameRules: gameRules.G6S,
    },
    {
      gameMethod: '二星-前二直选复式',
      methodId: 'F2IO',
      gameRules: gameRules.F2IO,
    },
    {
      gameMethod: '二星-前二直选单式',
      betMode: 'single',
      inputMode: 'text',
      methodId: 'F2IO',
      gameRules: gameRules.F2IO,
    },
    {
      gameMethod: '二星-后二直选复式',
      methodId: 'L2IO',
      gameRules: gameRules.L2IO,
    },
    {
      gameMethod: '二星-后二直选单式',
      betMode: 'single',
      inputMode: 'text',
      methodId: 'L2IO',
      gameRules: gameRules.L2IO,
    },
    {
      gameMethod: '二星-前二组选复式',
      methodId: 'F2',
      gameRules: gameRules.GRP2,
    },
    {
      gameMethod: '二星-前二组选单式',
      betMode: 'single',
      inputMode: 'text',
      methodId: 'F2',
      gameRules: gameRules.GRP2,
    },
    {
      gameMethod: '二星-后二组选复式',
      methodId: 'L2',
      gameRules: gameRules.GRP2,
    },
    {
      gameMethod: '二星-后二组选单式',
      betMode: 'single',
      inputMode: 'text',
      methodId: 'L2',
      gameRules: gameRules.GRP2,
    },
    {
      gameMethod: '定位胆',
      methodId: 'SP',
      gameRules: gameRules.SP,
    },
    {
      gameMethod: '不定位-一码不定位',
      methodId: 'NS1P',
      gameRules: gameRules.UNFIX_1,
    },
    {
      gameMethod: '不定位-二码不定位',
      methodId: 'NS2P',
      gameRules: gameRules.UNFIX_2,
    },
    {
      gameMethod: '大小单双-后二大小单双',
      methodId: 'L2BSOE',
      gameRules: {...gameRules.BSOE2, sections: type.UNITS_S_G},
    },
    {
      gameMethod: '大小单双-前二大小单双',
      methodId: 'F2BSOE',
      gameRules: {...gameRules.BSOE2, sections: type.UNITS_B_S},
    },
    {
      gameMethod: '轮盘',
      methodId: 'LP',
      isLunpan: true,
      gameRules: {...gameRules.LP},
    },
  ],
  [PCDANDAN]: [
    {
      gameMethod: '混合',
      methodId: 'MIX',
      gameRules: {
        sections: type.MIX,
        set: [type.BS_DS_EXTEND],
        formula: type.SINGLE,
        minimumRowPick: 1,
        pickRange: ['1-10'],
      },
    },
    {
      gameMethod: '特码',
      methodId: 'SP',
      gameRules: {
        sections: type.SPECIAL_NUM,
        set: [type.NUM_0_27],
        formula: type.SINGLE,
        minimumRowPick: 1,
        pickRange: ['1-28'],
      },
    },
    {
      gameMethod: '特码-特码包三',
      methodId: 'SP3',
      gameRules: {
        sections: type.BUNDLE_THREE,
        set: [type.NUM_0_27],
        isUnique: true,
        formula: type.BUNDLING_THREE,
        minimumRowPick: 1,
        pickRange: ['3-3'],
      },
    },
    {
      gameMethod: '波色',
      methodId: 'BS',
      gameRules: {
        sections: type.COLOR_BALL,
        set: [type.COLOR_THREE],
        formula: type.SINGLE,
        minimumRowPick: 1,
        pickRange: ['1-3'],
      },
    },
    {
      gameMethod: '豹子',
      methodId: 'BZ',
      gameRules: {
        sections: type.LEOPARD,
        set: [type.LEOPARD],
        formula: type.SINGLE,
        minimumRowPick: 1,
        pickRange: ['1-1'],
      },
    },
    {
      gameMethod: '轮盘',
      methodId: 'LP',
      isLunpan: true,
      gameRules: {...gameRules.LP},
    },
  ],
  [KUAI3]: [
    {
      gameMethod: '和值',
      methodId: 'HZ',
      gameRules: {
        sections: type.SUM_VALUES,
        set: [type.NUM_3_18],
        formula: type.SINGLE,
        minimumRowPick: 1,
        pickRange: ['1-16'],
      },
    },
    {
      gameMethod: '和值-和值大小单双',
      methodId: 'SUM',
      gameRules: {...gameRules.BS_DS, sections: type.SUM_VALUES},
    },
    {
      gameMethod: '三同号-三同号通选',
      methodId: 'STHTX',
      displayOverwrite: true,
      gameRules: {...gameRules.SHTX, displaySet: [['三同号通选']]},
    },
    {
      gameMethod: '三同号-三同号单选',
      methodId: 'STHDX',
      displayOverwrite: true,
      gameRules: {
        sections: type.PICK_NUM,
        set: [type.NUM_1_6],
        formula: type.SINGLE,
        displaySet: [type.TRIPLE_SAME_1_6],
        minimumRowPick: 1,
        pickRange: ['1-6'],
      },
    },
    {
      gameMethod: '三不同号',
      methodId: 'SBTH',
      gameRules: {
        sections: type.PICK_NUM,
        set: [type.NUM_1_6],
        formula: type.DIRECT_COMBINE,
        minimumRowPick: 1,
        pickRange: ['3-6'],
      },
    },
    {
      gameMethod: '三连号通选',
      methodId: 'SLHTX',
      displayOverwrite: true,
      gameRules: {...gameRules.SHTX, displaySet: [['三连号通选']]},
    },
    {
      gameMethod: '二同号-二同号复选',
      methodId: 'ETHFX',
      gameRules: {
        sections: type.PICK_NUM,
        set: [type.DOUBLE_SAME_1_6__SINGLE],
        joinPickWith: [','],
        joinSectionWith: ',',
        formula: type.SINGLE,
        minimumRowPick: 1,
        pickRange: ['1-6'],
      },
    },
    {
      gameMethod: '二同号-二同号单选',
      methodId: 'ETHDX',
      gameRules: {
        sections: type.SAME_UNSAME,
        set: [type.DOUBLE_SAME_1_6, type.NUM_1_6],
        formula: type.DUPLEX,
        minimumRowPick: 2,
        pickRange: ['1-6', '1-6'],
        isUnique: true,
      },
    },
    {
      gameMethod: '二不同号',
      methodId: 'EBTH',
      gameRules: {
        sections: type.PICK_NUM,
        set: [type.NUM_1_6],
        formula: type.DIRECT_COMBINE,
        minimumRowPick: 1,
        pickRange: ['2-6'],
      },
    },
    {
      gameMethod: '二不同号-二不同号胆拖',
      methodId: 'EBTHDT',
      gameRules: {
        ...gameRules.DT,
        set: [type.NUM_1_6],
        uniqueInt: 2,
        pickRange: ['1-1', '1-6'],
      },
    },
    {
      gameMethod: '猜一个号',
      methodId: 'NCYG',
      gameRules: {
        sections: type.PICK_NUM,
        set: [type.NUM_1_6],
        uniqueInt: 1,
        formula: type.DIRECT_MULTIPLY,
        minimumRowPick: 1,
        pickRange: ['1-6'],
      },
    },
    {
      gameMethod: '跨',
      methodId: 'KUA',
      gameRules: {
        sections: type.PICK_NUMBER,
        set: [type.KUA_NUM],
        uniqueInt: 1,
        formula: type.DIRECT_MULTIPLY,
        minimumRowPick: 1,
        pickRange: ['1-5'],
      },
    },
  ],
  [HAPPY10]: [
    {
      gameMethod: '首位-首位数投',
      methodId: 'ST1',
      gameRules: {
        sections: type.FIRST,
        set: [type.LEADNUM_1_18],
        formula: type.DUPLEX,
        minimumRowPick: 1,
        pickRange: ['1-18'],
      },
    },
    {
      gameMethod: '首位-首位红投',
      methodId: 'RT1',
      gameRules: {
        sections: type.PUPOLAR_PICK,
        set: [type.LEADNUM_19_20],
        formula: type.DUPLEX,
        minimumRowPick: 1,
        pickRange: ['1-2'],
      },
    },

    {
      gameMethod: '二连-二连直',
      methodId: 'DC2',
      gameRules: {
        sections: type.FRONT_BACK,
        set: [type.LEADNUM_1_20],
        formula: type.TOP_TWO_BET,
        minimumRowPick: 2,
        pickRange: ['1-20', '1-20'],
      },
    },
    {
      gameMethod: '二连-二连组',
      methodId: 'CC2',
      gameRules: {
        sections: type.GROUP_TWO,
        set: [type.LEADNUM_1_20],
        formula: type.DIRECT_COMBINE,
        minimumRowPick: 1,
        pickRange: ['2-20'],
      },
    },

    {
      gameMethod: '前三-前三直',
      methodId: 'DT3',
      gameRules: {
        sections: type.TOP_THREE_PLACE,
        set: [type.LEADNUM_1_20],
        formula: type.TOP_THREE_BET,
        minimumRowPick: 3,
        pickRange: ['1-20', '1-20', '1-20'],
      },
    },
    {
      gameMethod: '前三-前三组',
      methodId: 'CT3',
      gameRules: {
        sections: type.GROUP_THREE,
        set: [type.LEADNUM_1_20],
        formula: type.DIRECT_COMBINE,
        minimumRowPick: 1,
        pickRange: ['3-20'],
      },
    },
    {
      gameMethod: '快乐-快乐二',
      methodId: 'KL2',
      gameRules: {
        ...gameRules.KL,
        sections: type.HAPPY_TWO,
        pickRange: ['2-20'],
      },
    },
    {
      gameMethod: '快乐-快乐三',
      methodId: 'KL3',
      gameRules: {
        ...gameRules.KL,
        sections: type.HAPPY_THREE,
        pickRange: ['3-20'],
      },
    },
    {
      gameMethod: '快乐-快乐四',
      methodId: 'KL4',
      gameRules: {
        ...gameRules.KL,
        sections: type.HAPPY_FOUR,
        pickRange: ['4-20'],
      },
    },
    {
      gameMethod: '快乐-快乐五',
      methodId: 'KL5',
      gameRules: {
        ...gameRules.KL,
        sections: type.HAPPY_FIVE,
        pickRange: ['5-20'],
      },
    },
  ],
  [SIX]: [
    {
      gameMethod: '特码-特码B盘',
      methodId: 'SB',
      gameRules: gameRules.PN_D,
    },
    {
      gameMethod: '特码-特码A盘',
      methodId: 'SA',
      gameRules: gameRules.PN_D,
    },
    {
      gameMethod: '两面',
      methodId: 'BS',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.SPECIAL_SYMBOLICS],
        formula: type.DUPLEX,
        minimumRowPick: 1,
        pickRange: ['1-24'],
      },
    },
    {
      gameMethod: '色波',
      methodId: 'C',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.COLOR_NUM],
        isGroupBtn: true,
        formula: type.SINGLE,
        minimumRowPick: 1,
        pickRange: ['1-3'],
      },
    },
    {
      gameMethod: '色波-半波',
      methodId: 'C',
      gameRules: {...gameRules.C_D, set: [type.MIX_TWO]},
    },
    {
      gameMethod: '色波-半半波',
      methodId: 'C',
      gameRules: {...gameRules.C_D, set: [type.MIX_THREE]},
    },
    {
      gameMethod: '特肖-生肖',
      methodId: 'SX',
      gameRules: {...gameRules.C_D, set: [type.SYMBOLICS]},
    },
    {
      gameMethod: '头尾数',
      methodId: 'SHT',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.HEAD_TAIL_NUM],
        formula: type.DUPLEX,
        minimumRowPick: 1,
        pickRange: ['1-15'],
      },
    },
    {
      gameMethod: '正码',
      methodId: 'NG',
      gameRules: gameRules.PN_D,
    },
    {
      gameMethod: '正码特-正一特',
      methodId: 'NGB1',
      gameRules: gameRules.PN_S,
    },
    {
      gameMethod: '正码特-正二特',
      methodId: 'NGB2',
      gameRules: gameRules.PN_S,
    },
    {
      gameMethod: '正码特-正三特',
      methodId: 'NGB3',
      gameRules: gameRules.PN_S,
    },
    {
      gameMethod: '正码特-正四特',
      methodId: 'NGB4',
      gameRules: gameRules.PN_S,
    },
    {
      gameMethod: '正码特-正五特',
      methodId: 'NGB5',
      gameRules: gameRules.PN_S,
    },
    {
      gameMethod: '正码特-正六特',
      methodId: 'NGB6',
      gameRules: gameRules.PN_S,
    },
    {
      gameMethod: '正码1~6-正码1',
      methodId: 'NG1261',
      gameRules: gameRules.C_S,
    },
    {
      gameMethod: '正码1~6-正码2',
      methodId: 'NG1262',
      gameRules: gameRules.C_S,
    },
    {
      gameMethod: '正码1~6-正码3',
      methodId: 'NG1263',
      gameRules: gameRules.C_S,
    },
    {
      gameMethod: '正码1~6-正码4',
      methodId: 'NG1264',
      gameRules: gameRules.C_S,
    },
    {
      gameMethod: '正码1~6-正码5',
      methodId: 'NG1265',
      gameRules: gameRules.C_S,
    },
    {
      gameMethod: '正码1~6-正码6',
      methodId: 'NG1266',
      gameRules: gameRules.C_S,
    },
    {
      gameMethod: '五行',
      methodId: 'FX',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.FIVE_ELEMENTS],
        formula: type.DUPLEX,
        minimumRowPick: 1,
        pickRange: ['1-5'],
      },
    },
    {
      gameMethod: '平特-新平特一肖',
      methodId: 'NGSX',
      gameRules: {...gameRules.C_D, set: [type.SYMBOLICS]},
    },
    {
      gameMethod: '平特-新平特尾数',
      methodId: 'NGST',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.TAIL_NUM],
        formula: type.DUPLEX,
        minimumRowPick: 1,
        pickRange: ['1-10'],
      },
    },
    {
      gameMethod: '正肖-生肖',
      methodId: 'GX',
      gameRules: {...gameRules.C_D, set: [type.SYMBOLICS]},
    },
    {
      gameMethod: '七色波',
      methodId: 'SC',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.COLOR_THREE_DRAW],
        formula: type.DUPLEX,
        minimumRowPick: 1,
        pickRange: ['1-4'],
      },
    },
    {
      gameMethod: '总肖',
      methodId: 'XC',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.TOTAL_SYMBOLICS],
        formula: type.DUPLEX,
        minimumRowPick: 1,
        pickRange: ['1-8'],
      },
    },
    {
      gameMethod: '自选不中-五不中',
      methodId: 'NB5',
      gameRules: {...gameRules.NB, pickRange: ['5-10']},
    },
    {
      gameMethod: '自选不中-六不中',
      methodId: 'NB6',
      gameRules: {...gameRules.NB, pickRange: ['6-10']},
    },
    {
      gameMethod: '自选不中-七不中',
      methodId: 'NB7',
      gameRules: {...gameRules.NB, pickRange: ['7-10']},
    },
    {
      gameMethod: '自选不中-八不中',
      methodId: 'NB8',
      gameRules: {...gameRules.NB, pickRange: ['8-11']},
    },
    {
      gameMethod: '自选不中-九不中',
      methodId: 'NB9',
      gameRules: {...gameRules.NB, pickRange: ['9-12']},
    },
    {
      gameMethod: '自选不中-十不中',
      methodId: 'NB10',
      gameRules: {...gameRules.NB, pickRange: ['10-13']},
    },
    {
      gameMethod: '自选不中-十一不中',
      methodId: 'NB11',
      gameRules: {...gameRules.NB, pickRange: ['11-13']},
    },
    {
      gameMethod: '自选不中-十二不中',
      methodId: 'NB12',
      gameRules: {...gameRules.NB, pickRange: ['12-14']},
    },
    {
      gameMethod: '连肖连尾-二连肖',
      methodId: 'XB2',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.SYMBOLICS],
        uniqueInt: 2,
        formula: type.GROUP_2,
        minimumRowPick: 1,
        pickRange: ['2-12'],
      },
    },
    {
      gameMethod: '连肖连尾-三连肖',
      methodId: 'XB3',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.SYMBOLICS],
        formula: type.GROUP_6,
        minimumRowPick: 1,
        pickRange: ['3-12'],
      },
    },
    {
      gameMethod: '连肖连尾-四连肖',
      methodId: 'XB4',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.SYMBOLICS],
        uniqueInt: 4,
        formula: type.SYMBOLIC_CONNECT_FOUR,
        minimumRowPick: 1,
        pickRange: ['4-12'],
      },
    },
    {
      gameMethod: '连肖连尾-五连肖',
      methodId: 'XB5',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.SYMBOLICS],
        formula: type.DIRECT_COMBINE,
        minimumRowPick: 1,
        pickRange: ['5-12'],
      },
    },
    {
      gameMethod: '连肖连尾-二连尾',
      methodId: 'TB2',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.TAIL_NUM],
        uniqueInt: 2,
        formula: type.GROUP_2,
        minimumRowPick: 1,
        pickRange: ['2-10'],
      },
    },
    {
      gameMethod: '连肖连尾-三连尾',
      methodId: 'TB3',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.TAIL_NUM],
        formula: type.GROUP_6,
        minimumRowPick: 1,
        pickRange: ['3-10'],
      },
    },
    {
      gameMethod: '连肖连尾-四连尾',
      methodId: 'TB4',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.TAIL_NUM],
        uniqueInt: 4,
        formula: type.SYMBOLIC_CONNECT_FOUR,
        minimumRowPick: 1,
        pickRange: ['4-10'],
      },
    },
    {
      gameMethod: '连肖连尾-五连尾',
      methodId: 'TB5',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.TAIL_NUM],
        formula: type.DIRECT_COMBINE,
        minimumRowPick: 1,
        pickRange: ['5-10'],
      },
    },
    {
      gameMethod: '合肖',
      methodId: 'GRPX',
      gameRules: {
        sections: type.CATEGORY,
        set: [type.SYMBOLICS],
        formula: type.SYMBOLICS_BINGO,
        minimumRowPick: 1,
        pickRange: ['2-11'],
      },
    },
    {
      gameMethod: '连码-三中二',
      methodId: 'LM3Z2',
      gameRules: {...gameRules.LM3, pickRange: ['3-10']},
    },
    {
      gameMethod: '连码-三全中',
      methodId: 'LM3QZ',
      gameRules: {...gameRules.LM3, pickRange: ['3-10']},
    },
    {
      gameMethod: '连码-二全中',
      methodId: 'LM2QZ',
      gameRules: gameRules.LM2_10,
    },
    {
      gameMethod: '连码-二中特',
      methodId: 'LM2ZT',
      gameRules: gameRules.LM2_10,
    },
    {
      gameMethod: '连码-特串',
      methodId: 'LMTC',
      gameRules: {
        ...gameRules.LM2,
        pickRange: ['2-10'],
      },
    },
    {
      gameMethod: '连码-四全中',
      methodId: 'LM4QZ',
      gameRules: {
        sections: type.PICK_NUM,
        set: [type.LEADNUM_1_49],
        uniqueInt: 4,
        isUnique: true,
        formula: type.CONNECT_NUM_4,
        minimumRowPick: 1,
        pickRange: ['4-10'],
      },
    },
  ],
  [PK]: [
    {
      gameMethod: '包选',
      methodId: 'BX',
      isPoker: true,
      gameRules: {
        sections: type.PICK_CARD,
        set: [type.POKER_BX],
        displaySet: type.POKER_BX_DISPLAY_TEXT,
        formula: type.SINGLE,
        minimumRowPick: 1,
        pickRange: ['1-5'],
        showMethod: true,
      },
    },
    {
      gameMethod: '两面',
      methodId: 'LM',
      isPoker: true,
      gameRules: {
        sections: type.PICK_CARD,
        set: [type.POKER_LM],
        displaySet: type.POKER_LM,
        formula: type.SINGLE,
        minimumRowPick: 1,
        pickRange: ['1-11'],
        showMethod: true,
        isNum: true,
      },
    },
    {
      gameMethod: '单选-同花单选',
      methodId: 'THDX',
      isPoker: true,
      gameRules: {
        ...gameRules.THDX,
        set: [type.POKER_THDX],
        displaySet: type.POKER_THDX_DISPLAY_TEXT,
      },
    },
    {
      gameMethod: '单选-顺子单选',
      methodId: 'SZDX',
      isPoker: true,
      gameRules: {
        sections: type.PICK_CARD,
        set: [type.POKER_SZDX],
        displaySet: type.POKER_SZDX_DISPLAY_TEXT,
        formula: type.SINGLE,
        minimumRowPick: 1,
        pickRange: ['1-12'],
      },
    },
    {
      gameMethod: '单选-同花顺单选',
      methodId: 'THSDX',
      isPoker: true,
      gameRules: {
        ...gameRules.THDX,
        set: [type.POKER_THSDX],
        displaySet: type.POKER_THSDX_DISPLAY_TEXT,
      },
    },
    {
      gameMethod: '单选-豹子单选',
      methodId: 'BZDX',
      isPoker: true,
      gameRules: {
        ...gameRules.ZDX,
        set: [type.POKER_BZDX],
        displaySet: type.POKER_BZDX_DISPLAY_TEXT,
      },
    },
    {
      gameMethod: '单选-对子单选',
      methodId: 'DZDX',
      isPoker: true,
      gameRules: {
        ...gameRules.ZDX,
        set: [type.POKER_DZDX],
        displaySet: type.POKER_DZDX_DISPLAY_TEXT,
      },
    },
    {
      gameMethod: '任选-任选一',
      methodId: 'NR1',
      isPoker: true,
      gameRules: {
        sections: type.PICK_CARD,
        set: [type.POKER_NRX_DISPLAY_TEXT],
        displaySet: type.POKER_NRX_DISPLAY_TEXT,
        minimumRowPick: 1,
        formula: type.SYMBOLICS_BINGO,
        pickRange: ['1-15'],
        mixBetString: type.NEW_RX_MIXBETSTRING,
        isUnique: true,
      },
    },
    {
      gameMethod: '任选-任选二',
      methodId: 'NR2',
      isPoker: true,
      gameRules: {
        sections: type.PICK_CARD,
        set: [type.POKER_NRX_DISPLAY_TEXT],
        displaySet: type.POKER_NRX_DISPLAY_TEXT,
        minimumRowPick: 1,
        formula: type.SYMBOLICS_BINGO,
        pickRange: ['2-26'],
        mixBetString: type.NEW_RX_MIXBETSTRING,
        isUnique: true,
      },
    },
    {
      gameMethod: '任选-任选三',
      methodId: 'NR3',
      isPoker: true,
      gameRules: {
        sections: type.PICK_CARD,
        set: [type.POKER_NRX_DISPLAY_TEXT],
        displaySet: type.POKER_NRX_DISPLAY_TEXT,
        minimumRowPick: 1,
        formula: type.SYMBOLICS_BINGO,
        pickRange: ['3-42'],
        mixBetString: type.NEW_RX_MIXBETSTRING,
        isUnique: true,
      },
    },
    {
      gameMethod: '任选-任选一',
      methodId: 'R1',
      isPoker: true,
      gameRules: {...gameRules.RC, formula: type.SINGLE, pickRange: ['1-13']},
    },
    {
      gameMethod: '任选-任选二',
      methodId: 'R2',
      isPoker: true,
      gameRules: {...gameRules.RC, pickRange: ['2-13']},
    },
    {
      gameMethod: '任选-任选三',
      methodId: 'R3',
      isPoker: true,
      gameRules: {...gameRules.RC, pickRange: ['3-13']},
    },
    {
      gameMethod: '任选-任选四',
      methodId: 'R4',
      isPoker: true,
      gameRules: {...gameRules.RC, pickRange: ['4-13']},
    },
    {
      gameMethod: '任选-任选五',
      methodId: 'R5',
      isPoker: true,
      gameRules: {...gameRules.RC, pickRange: ['5-13']},
    },
    {
      gameMethod: '任选-任选六',
      methodId: 'R6',
      isPoker: true,
      gameRules: {...gameRules.RC, pickRange: ['6-13']},
    },
  ],
  [SHISHICAI]: [
    {
      gameMethod: '定位胆',
      methodId: 'DN',
      gameRules: {
        sections: type.UNITS_W_Q_B_S_G,
        set: [type.NUM_0_9],
        formula: type.SINGLE,
        minimumRowPick: 1,
        pickRange: ['1-10', '1-10', '1-10', '1-10', '1-10'],
      },
    },
    {
      gameMethod: '五星-通选复式',
      methodId: 'C5',
      gameRules: gameRules.D5,
    },
    {
      gameMethod: '五星-通选单式',
      methodId: 'C5',
      betMode: 'single',
      inputMode: 'text',
      gameRules: gameRules.D5,
    },
    {
      gameMethod: '五星-直选复式',
      methodId: 'D5',
      gameRules: gameRules.D5,
    },
    {
      gameMethod: '五星-直选单式',
      methodId: 'D5',
      betMode: 'single',
      inputMode: 'text',
      gameRules: gameRules.D5,
    },
    {
      gameMethod: '三星-直选复式',
      methodId: 'D3',
      gameRules: {...gameRules.D3, formula: type.DUPLEX},
    },
    {
      gameMethod: '三星-直选单式',
      methodId: 'D3',
      betMode: 'single',
      inputMode: 'text',
      gameRules: {...gameRules.D3, formula: type.DUPLEX},
    },
    {
      gameMethod: '三星-组三复式',
      methodId: 'C33',
      gameRules: gameRules.GRP3,
    },
    {
      gameMethod: '三星-组三单式',
      betMode: 'single',
      inputMode: 'text',
      methodId: 'C33DS',
      gameRules: {
        ...gameRules.GRP3,
        formula: type.GROUP_3__SINGLE,
        pickRange: ['3-10'],
        specialCond: {duplicate: {no: 1, occurence: 2}},
      },
    },
    {
      gameMethod: '三星-组六复式',
      methodId: 'C36',
      gameRules: gameRules.GRP6,
    },
    {
      gameMethod: '三星-组六单式',
      methodId: 'C36',
      betMode: 'single',
      inputMode: 'text',
      gameRules: gameRules.GRP6,
    },
    {
      gameMethod: '二星-直选复式',
      methodId: 'D2',
      gameRules: gameRules.D2,
    },
    {
      gameMethod: '二星-直选单式',
      methodId: 'D2',
      betMode: 'single',
      inputMode: 'text',
      gameRules: gameRules.D2,
    },
    {
      gameMethod: '二星-组选复式',
      methodId: 'C2',
      gameRules: gameRules.GRP2,
    },
    {
      gameMethod: '二星-组选单式',
      methodId: 'C2',
      betMode: 'single',
      inputMode: 'text',
      gameRules: gameRules.GRP2,
    },
    {
      gameMethod: '大小单双-后二位',
      methodId: 'DXDS',
      gameRules: {...gameRules.BSOE2, sections: type.UNITS_S_G},
    },
    {
      gameMethod: '大小单双-后三位',
      methodId: 'DXDS_H3',
      gameRules: {...gameRules.BSOE3, sections: type.UNITS_B_S_G},
    },
    {
      gameMethod: '大小单双-前二位',
      methodId: 'DXDS_Q2',
      gameRules: {...gameRules.BSOE2, sections: type.UNITS_W_Q},
    },
    {
      gameMethod: '大小单双-前三位',
      methodId: 'DXDS_Q3',
      gameRules: {...gameRules.BSOE3, sections: type.UNITS_W_Q_B},
    },
    {
      gameMethod: '大小单双-万位',
      methodId: 'WW',
      gameRules: {...gameRules.BSOE, sections: type.UNITS_W},
    },
    {
      gameMethod: '大小单双-千位',
      methodId: 'QW',
      gameRules: {...gameRules.BSOE, sections: type.UNITS_Q},
    },
    {
      gameMethod: '大小单双-百位',
      methodId: 'BW',
      gameRules: {...gameRules.BSOE, sections: type.UNITS_B},
    },
    {
      gameMethod: '大小单双-十位',
      methodId: 'SW',
      gameRules: {...gameRules.BSOE, sections: type.UNITS_S},
    },
    {
      gameMethod: '大小单双-个位',
      methodId: 'GW',
      gameRules: {...gameRules.BSOE, sections: type.UNITS_G},
    },
    {
      gameMethod: '不定位-前三一码',
      methodId: 'BDW_Q31',
      gameRules: gameRules.UNFIX_1,
    },
    {
      gameMethod: '不定位-前三二码',
      methodId: 'BDW_Q32',
      gameRules: gameRules.UNFIX_2,
    },
    {
      gameMethod: '不定位-后三一码',
      methodId: 'BDW_H31',
      gameRules: gameRules.UNFIX_1,
    },
    {
      gameMethod: '不定位-后三二码',
      methodId: 'BDW_H32',
      gameRules: gameRules.UNFIX_2,
    },
    {
      gameMethod: '不定位-前四一码',
      methodId: 'BDW_Q41',
      gameRules: gameRules.UNFIX_1,
    },
    {
      gameMethod: '不定位-前四二码',
      methodId: 'BDW_Q42',
      gameRules: gameRules.UNFIX_2,
    },
    {
      gameMethod: '不定位-后四一码',
      methodId: 'BDW_H41',
      gameRules: gameRules.UNFIX_1,
    },
    {
      gameMethod: '不定位-后四二码',
      methodId: 'BDW_H42',
      gameRules: gameRules.UNFIX_2,
    },
    {
      gameMethod: '不定位-五星一码',
      methodId: 'BDW_Q51',
      gameRules: gameRules.UNFIX_1,
    },
    {
      gameMethod: '不定位-五星二码',
      methodId: 'BDW_Q52',
      gameRules: gameRules.UNFIX_2,
    },
    {
      gameMethod: '不定位-五星三码',
      methodId: 'BDW_Q53',
      gameRules: {
        sections: type.UNFIX,
        set: [type.NUM_0_9],
        formula: type.DIRECT_COMBINE,
        minimumRowPick: 1,
        pickRange: ['3-10'],
      },
    },
    {
      gameMethod: '任选二-直选',
      methodId: 'R2Z',
      gameRules: {...gameRules.RZ, minimumRowPick: 2},
    },
    {
      gameMethod: '任选二-直选和值',
      methodId: 'R2Z_HZ',
      gameRules: gameRules.R2C_HZ,
    },
    {
      gameMethod: '任选二-组选',
      methodId: 'R2C',
      gameRules: {
        sections: type.PICK_GROUP,
        set: [type.NUM_0_9],
        openOptions: type.UNITS_W_Q_B_S_G,
        formula: type.GROUP_2__OPEN,
        minimumRowPick: 1,
        pickRange: ['2-10'],
        uniqueInt: 2,
      },
    },
    {
      gameMethod: '任选二-组选和值',
      methodId: 'R2C_HZ',
      gameRules: gameRules.R2C_HZ,
    },
    {
      gameMethod: '任选三-直选',
      methodId: 'R3Z',
      gameRules: {...gameRules.RZ, minimumRowPick: 3},
    },
    {
      gameMethod: '任选三-直选和值',
      methodId: 'R3Z_HZ',
      gameRules: gameRules.R3C_HZ,
    },
    {
      gameMethod: '任选三-组三',
      methodId: 'R3C3',
      gameRules: {
        ...gameRules.R3C,
        formula: type.GROUP_3__OPEN,
        pickRange: ['2-10'],
      },
    },
    {
      gameMethod: '任选三-组六',
      methodId: 'R3C6',
      gameRules: {
        ...gameRules.R3C,
        formula: type.GROUP_6__OPEN,
        pickRange: ['3-10'],
      },
    },
    {
      gameMethod: '任选三-组选和值',
      methodId: 'R3C_HZ',
      gameRules: gameRules.R3C_HZ,
    },
    {
      gameMethod: '任选四-直选',
      methodId: 'R4Z',
      gameRules: {...gameRules.RZ, minimumRowPick: 4},
    },
    {
      gameMethod: '任选四-组选24',
      methodId: 'R4C24',
      gameRules: {
        sections: type.PICK_GROUP_24,
        set: [type.NUM_0_9],
        openOptions: type.UNITS_W_Q_B_S_G,
        formula: type.GROUP_PICK_24__OPEN,
        minimumRowPick: 1,
        pickRange: ['4-10'],
        uniqueInt: 4,
      },
    },
    {
      gameMethod: '任选四-组选12',
      methodId: 'R4C12',
      gameRules: {
        sections: type.DOUBLE_SINGLE_NUM,
        set: [type.NUM_0_9],
        openOptions: type.UNITS_W_Q_B_S_G,
        formula: type.GROUP_PICK_12__OPEN,
        minimumRowPick: 2,
        pickRange: ['1-10', '2-10'],
        uniqueInt: 4,
      },
    },
    {
      gameMethod: '任选四-组选6',
      methodId: 'R4C6',
      gameRules: {
        sections: type.TRIPLE_SINGLE_NUM,
        set: [type.NUM_0_9],
        openOptions: type.UNITS_W_Q_B_S_G,
        formula: type.GROUP_PICK_6__OPEN,
        minimumRowPick: 1,
        pickRange: ['2-10'],
        uniqueInt: 4,
      },
    },
    {
      gameMethod: '任选四-组选4',
      methodId: 'R4C4',
      gameRules: {
        sections: type.DOUBLE_NUM,
        set: [type.NUM_0_9],
        openOptions: type.UNITS_W_Q_B_S_G,
        formula: type.GROUP_PICK_4__OPEN,
        minimumRowPick: 2,
        pickRange: ['1-10', '1-10'],
        uniqueInt: 4,
      },
    },
    {
      gameMethod: '大小单双-总和',
      methodId: 'SUM',
      gameRules: {...gameRules.BSOE, sections: type.TOTAL_SUMS},
    },
    {
      gameMethod: '龙虎斗-万千位',
      methodId: 'TND_54',
      gameRules: gameRules.TND,
    },
    {
      gameMethod: '龙虎斗-万百位',
      methodId: 'TND_53',
      gameRules: gameRules.TND,
    },
    {
      gameMethod: '龙虎斗-万十位',
      methodId: 'TND_52',
      gameRules: gameRules.TND,
    },
    {
      gameMethod: '龙虎斗-万个位',
      methodId: 'TND_51',
      gameRules: gameRules.TND,
    },
    {
      gameMethod: '龙虎斗-千百位',
      methodId: 'TND_43',
      gameRules: gameRules.TND,
    },
    {
      gameMethod: '龙虎斗-千十位',
      methodId: 'TND_42',
      gameRules: gameRules.TND,
    },
    {
      gameMethod: '龙虎斗-千个位',
      methodId: 'TND_41',
      gameRules: gameRules.TND,
    },
    {
      gameMethod: '龙虎斗-百十位',
      methodId: 'TND_32',
      gameRules: gameRules.TND,
    },
    {
      gameMethod: '龙虎斗-百个位',
      methodId: 'TND_31',
      gameRules: gameRules.TND,
    },
    {
      gameMethod: '龙虎斗-十个位',
      methodId: 'TND_21',
      gameRules: gameRules.TND,
    },
    {
      gameMethod: '顺子-前三位',
      methodId: 'POKER_Q3',
      gameRules: {...gameRules.POKER3, sections: type.FRONT_THREE},
    },
    {
      gameMethod: '顺子-中三位',
      methodId: 'POKER_Z3',
      gameRules: {...gameRules.POKER3, sections: type.CENTER_THREE},
    },
    {
      gameMethod: '顺子-后三位',
      methodId: 'POKER_H3',
      gameRules: {...gameRules.POKER3, sections: type.BACK_THREE},
    },
    {
      gameMethod: '斗牛',
      methodId: 'DOUNIU',
      gameRules: {
        sections: type.COW,
        set: [type.FIGHT_COW],
        formula: type.SINGLE,
        minimumRowPick: 1,
        pickRange: ['1-11'],
      },
    },
    {
      gameMethod: '轮盘',
      methodId: 'LP',
      isLunpan: true,
      gameRules: {...gameRules.LP},
    },
  ],
  [XY]: [
    {
      gameMethod: '定位胆',
      methodId: 'DN',
      gameRules: gameRules.DN,
    },
    {
      gameMethod: '猜第一',
      methodId: 'D1',
      gameRules: gameRules.D1,
    },
    {
      gameMethod: '猜前二',
      methodId: 'GT2',
      gameRules: gameRules.GT2,
    },
    {
      gameMethod: '猜前三',
      methodId: 'GT3',
      gameRules: gameRules.GT3,
    },
    {
      gameMethod: '后一',
      methodId: 'LAST1',
      gameRules: {...gameRules.D1, sections: type.BACK_FIRST_RANK},
    },
    {
      gameMethod: '后二',
      methodId: 'LAST2',
      gameRules: {...gameRules.GT2, sections: type.BACK_TWO_RANK},
    },
    {
      gameMethod: '后三',
      methodId: 'LAST3',
      gameRules: {...gameRules.GT3, sections: type.BACK_THREE_RANK},
    },
    {
      gameMethod: type.RANKS[0],
      methodId: 'D1M',
      gameRules: {...gameRules.DTBSOE, sections: [type.RANKS[0]]},
    },
    {
      gameMethod: type.RANKS[1],
      methodId: 'D2M',
      gameRules: {...gameRules.DTBSOE, sections: [type.RANKS[1]]},
    },
    {
      gameMethod: type.RANKS[2],
      methodId: 'D3M',
      gameRules: {...gameRules.DTBSOE, sections: [type.RANKS[2]]},
    },
    {
      gameMethod: type.RANKS[3],
      methodId: 'D4M',
      gameRules: {...gameRules.DTBSOE, sections: [type.RANKS[3]]},
    },
    {
      gameMethod: type.RANKS[4],
      methodId: 'D5M',
      gameRules: {...gameRules.DTBSOE, sections: [type.RANKS[4]]},
    },
    {
      gameMethod: type.RANKS[5],
      methodId: 'D6M',
      gameRules: {...gameRules.BSOE, sections: [type.RANKS[5]]},
    },
    {
      gameMethod: type.RANKS[6],
      methodId: 'D7M',
      gameRules: {...gameRules.BSOE, sections: [type.RANKS[6]]},
    },
    {
      gameMethod: type.RANKS[7],
      methodId: 'D8M',
      gameRules: {...gameRules.BSOE, sections: [type.RANKS[7]]},
    },
    {
      gameMethod: type.RANKS[8],
      methodId: 'D9M',
      gameRules: {...gameRules.BSOE, sections: [type.RANKS[8]]},
    },
    {
      gameMethod: type.RANKS[9],
      methodId: 'D10M',
      gameRules: {...gameRules.BSOE, sections: [type.RANKS[9]]},
    },
    {
      gameMethod: '冠亚和值',
      methodId: 'GYHZ',
      gameRules: gameRules.GYHZ,
    },
    {
      gameMethod: '冠亚和',
      methodId: 'GYH',
      gameRules: gameRules.GYH,
    },
  ],
  [QXC]: [
    {
      gameMethod: '普通-两定位',
      methodId: 'D2',
      gameRules: {
        sections: type.UNITS_Q_B_G_S,
        set: [type.NUM_0_9],
        formula: type.COMBO_DUPLEX,
        minimumRowPick: 2,
        pickRange: ['1-10', '1-10', '1-10', '1-10'],
      },
    },
    {
      gameMethod: '普通-三定位',
      methodId: 'D3',
      gameRules: {
        sections: type.UNITS_Q_B_G_S,
        set: [type.NUM_0_9],
        formula: type.COMBO_DUPLEX,
        minimumRowPick: 3,
        pickRange: ['1-10', '1-10', '1-10', '1-10'],
      },
    },
    {
      gameMethod: '普通-四定位',
      methodId: 'D4',
      gameRules: {
        sections: type.UNITS_Q_B_G_S,
        set: [type.NUM_0_9],
        formula: type.COMBO_DUPLEX,
        minimumRowPick: 4,
        pickRange: ['1-10', '1-10', '1-10', '1-10'],
      },
    },
    {
      gameMethod: '普通-一定位',
      methodId: 'D1',
      gameRules: {
        sections: type.UNITS_Q_B_G_S,
        set: [type.NUM_0_9],
        formula: type.SINGLE,
        minimumRowPick: 1,
        pickRange: ['1-10', '1-10', '1-10', '1-10'],
      },
    },
    {
      gameMethod: '普通-二字现',
      methodId: 'R2',
      gameRules: {
        sections: type.UNFIX,
        set: [type.NUM_0_9],
        formula: type.DIRECT_COMBINE,
        minimumRowPick: 1,
        pickRange: ['2-10'],
      },
    },
    {
      gameMethod: '普通-三字现',
      methodId: 'R3',
      gameRules: {
        sections: type.UNFIX,
        set: [type.NUM_0_9],
        formula: type.DIRECT_COMBINE,
        minimumRowPick: 1,
        pickRange: ['3-10'],
      },
    },
    {
      gameMethod: '大小单双-后二',
      methodId: 'DXDS_H2',
      gameRules: {...gameRules.BSOE2, sections: type.UNITS_S_G},
    },
    {
      gameMethod: '大小单双-后三',
      methodId: 'DXDS_H3',
      gameRules: {...gameRules.BSOE3, sections: type.UNITS_B_S_G},
    },
    {
      gameMethod: '大小单双-前二',
      methodId: 'DXDS_Q2',
      gameRules: {...gameRules.BSOE2, sections: type.UNITS_Q_B},
    },
    {
      gameMethod: '大小单双-前三',
      methodId: 'DXDS_Q3',
      gameRules: {...gameRules.BSOE3, sections: type.UNITS_Q_B_G},
    },
    {
      gameMethod: '大小单双-万位',
      methodId: 'DXDS_WW',
      gameRules: {...gameRules.BSOE, sections: type.UNITS_W},
    },
    {
      gameMethod: '大小单双-千位',
      methodId: 'DXDS_QW',
      gameRules: {...gameRules.BSOE, sections: type.UNITS_Q},
    },
    {
      gameMethod: '大小单双-百位',
      methodId: 'DXDS_BW',
      gameRules: {...gameRules.BSOE, sections: type.UNITS_B},
    },
    {
      gameMethod: '大小单双-十位',
      methodId: 'DXDS_SW',
      gameRules: {...gameRules.BSOE, sections: type.UNITS_S},
    },
    {
      gameMethod: '大小单双-个位',
      methodId: 'DXDS_GW',
      gameRules: {...gameRules.BSOE, sections: type.UNITS_G},
    },
    {
      gameMethod: '大小单双-总和',
      methodId: 'DXDS_SUM',
      gameRules: {...gameRules.BS_DS, sections: type.TOTAL_SUMS},
    },
  ],
};
